### ISSUE TITLE
Lancer pleins de tests et trouver le meilleur delta

### ISSUE THREAD

**Issue by Gouga34** [Gouga34/TERM1_Poker#209]

**Comment by Gouga34** [comment]
-- Delta 10 --
1000 parties avec réinitialisation caves :  465 parties // -23987jetons
1000 parties sans réinitialisation caves : 397 parties // -53861 jetons

**Comment by Manouel** [comment]
-- Delta 5 --
1000 parties avec réinitialisation caves : 48.4% parties // -32215 jetons
1000 parties sans réinitialisation caves : 30.7% parties // -24694 jetons

**Comment by Gouga34** [comment]
-- Delta 15 --
1000 parties avec réinitialisation caves : 471 parties // -12825 jetons
1000 parties sans réinitialisation caves : 420 parties // 16136 jetons

**Comment by Manouel** [comment]
-- Delta 3 --
1000 parties avec réinitialisation caves :  47.2% parties //   -52500 jetons
1000 parties sans réinitialisation caves :  29.2% parties //   -54194 jetons

**Comment by Manouel** [comment]
-- Delta 20 --
1000 parties avec réinitialisation caves : 45.9% parties // -56757 jetons
1000 parties sans réinitialisation caves : 34.5% parties // -23799 jetons

**Comment by Manouel** [comment]
Ah nan mais en fait sans reinitialisation cave faut changer dans le code la constante 1000 par une variable qui contient la cave de départ. Du coup mes résultats sont faux c pour ça 

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Mais du coup mes résultats aussi sont faux ? faut que je change quoi ds le code ?

**Comment by Gouga34** [comment]
-- Delta 13 --
1000 parties avec réinitialisation caves :   -- parties // -- jetons
1000 parties sans réinitialisation caves :428 parties // -45530 jetons
