### ISSUE TITLE
Possibilité de choisir en avance les cartes du jeu

### ISSUE THREAD

**Issue by Gouga34** [Gouga34/TERM1_Poker#40]
Permettre dans l'interface graphique de choisir la valeur des cartes du jeu (cartes du milieu, mains).

**Comment by Manouel** [comment]
Il faut rendre optionnel le choix des cartes (case à cocher).

**Comment by Gouga34** [comment]
ça serait sympa de pouvoir aussi choisir les cartes du milieu et du joueur adverse

**Comment by Gouga34** [comment]
Il faut pouvoir désactiver les cartes cochées si besoin
