### ISSUE TITLE
La partie se termine sans raison

### ISSUE THREAD

**Issue by Gouga34** [Gouga34/TERM1_Poker#75]
Lorsque l'on choisit les cartes avant de commencer la partie, la partie se finit au bout de x tours sans raison (aucun des deux joueurs ne se couchent et on n'arrive pas au river). On a alors "EGALITE" sans raison.

Cela arrive souvent avant que l'IA ne joue : problème de gestion des cartes choisies ?

**Comment by Manouel** [comment]
Pour les cartes choisies, j'ai vérifié le vecteur des identifiants qui est envoyé au jeu et il me semble correct.
